<ControlPanel>:
	MDCard:
		#size_hint_y: .85
		md_bg_color: app.theme_cls.bg_darkest
		radius: [20,10,20,10]
		BoxLayout:
			orientation: "vertical"
			MDToolbar:
				title: "Behaviours"
				size_hint_y: .1
				md_bg_color: color("#FF0066")
			CodeInput:
				text: "#Enter Behaviours Here"
				size_hint_y: .9
				#background_color: color("#000000")
				style_name: 'inkpot'			#paraiso-dark,inkpot,vim,native
				#color: color("#FFFFFF")
				#halign: "center"
